/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista.Paneles;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author eduardo
 */
public class login extends javax.swing.JPanel {

    /**
     * Creates new form login
     */
    public login() {
       
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        IP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        Conetar = new javax.swing.JButton();
        Iniciar_Servicio = new javax.swing.JButton();

        jLabel1.setText("IP : Puerto");

        jLabel2.setText("Nombre");

        Conetar.setText("Conectar");
        Conetar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConetarMouseClicked(evt);
            }
        });

        Iniciar_Servicio.setText("Iniciar Servicio");
        Iniciar_Servicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Iniciar_ServicioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(IP, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addComponent(nombre))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Conetar)
                        .addGap(18, 18, 18)
                        .addComponent(Iniciar_Servicio)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(IP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Conetar)
                    .addComponent(Iniciar_Servicio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ConetarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConetarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ConetarMouseClicked

    private void Iniciar_ServicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Iniciar_ServicioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Iniciar_ServicioMouseClicked

    public JButton getConetar() {
        return Conetar;
    }
    public JButton getIniciar_Servicio() {
        return Iniciar_Servicio;
    }
    public JTextField getIP() {
        return IP;
    }

    public void setIP(JTextField IP) {
        this.IP = IP;
    }

    public JTextField getNombre() {
        return nombre;
    }

    public void setNombre(JTextField nombre) {
        this.nombre = nombre;
    }
public JButton getconetar() {
        return Conetar;
    }
public JButton getIniciaServicio() {
        return Conetar;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Conetar;
    public javax.swing.JTextField IP;
    public javax.swing.JButton Iniciar_Servicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nombre;
    // End of variables declaration//GEN-END:variables
}
